# Generated by Django 4.2.6 on 2024-06-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_admin_productdb_rename_filename_cartitem_item_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
