# Generated by Django 4.2.6 on 2024-06-12 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_delete_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='code',
            new_name='img',
        ),
    ]
