# Generated by Django 4.2.6 on 2024-06-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
