# Generated by Django 4.2.6 on 2024-07-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_order_cancellationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='description',
            field=models.CharField(default='No Description', max_length=1000),
        ),
    ]
