# Generated by Django 4.2.6 on 2024-07-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_cartitem_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
