# Generated by Django 4.2.6 on 2024-07-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_productdb_img_productdb_delivery_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='product_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
