# Generated by Django 4.2.6 on 2024-07-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_cartitem_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='customer_care',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='productdb',
            name='fssai_info',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='productdb',
            name='key_features',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='productdb',
            name='return_policy',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='productdb',
            name='seller_details',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='productdb',
            name='shelf_life',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
