# Generated by Django 4.2.6 on 2024-07-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_productdb_customer_care_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='disclaimer',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
