# Generated by Django 4.2.6 on 2024-07-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_productdb_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='si_unit',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
