# Generated by Django 4.2.6 on 2024-07-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_productdb_si_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdb',
            name='stock',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
