# Generated by Django 4.2.6 on 2024-07-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_cartitem_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='delivery_fees',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='discount',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='other_fees',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='tax',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
